version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Moved to .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Moved to .env file
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initialization script

volumes:
  db_data:
